---
- hosts: dev
  become: true
  remote_user: ec2-user
  tasks:
    - name: Install Apache
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - httpd
        - php
        - php-mysql
    - name: Extract Wordpress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html
        owner: apache
        group: apache
        mode: '0755'
        remote_src: true
        extra_opts:
        - --strip-components=1
    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: true
